// @refresh reload
import "./root.css";
import { Suspense } from "solid-js";
import {
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Meta,
  Routes,
  Scripts,
  Title,
  Link,
} from "solid-start";
import { SessionProvider } from "@solid-auth/base/client";
import { trpc, queryClient } from "~/utils/trpc";
import Navbar from "./components/Navbar";

export default function Root() {
  return (
    <Html lang="en">
      <Head>
        <Title>Workout App</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta name="theme-color" content="#026d56" />
        <Meta name="description" content="Workout WebApp generated by create-jd-app" />
        <Meta name="author" content="Nicolas Bouffanais" />
        <Link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <trpc.Provider queryClient={queryClient}>
          <SessionProvider>
            <Navbar/>
            <Suspense>
              <ErrorBoundary>
                <Routes>
                  <FileRoutes />
                </Routes>
              </ErrorBoundary>
            </Suspense>
          </SessionProvider>
        </trpc.Provider>
        <Scripts />
      </Body>
    </Html>
  );
}
